server: 
  port: 8080

spring: 
  activemq: 
    broker-url: tcp://10.0.30.91:61616
    user: admin
    password: admin
    pool:
      enabled: true # true表示使用连接池；false时，每发送一条数据创建一个连接
      max-connections: 10 # 连接池最大连接数
      idle-timeout: 30000 # 空闲的连接过期时间，默认为30秒
      expiry-timeout: 0 # 强制的连接过期时间，与idleTimeout的区别在于：idleTimeout是在连接空闲一段时间失效，而expiryTimeout不管当前连接的情况，只要达到指定时间就失效。默认为0，never
  jms: 
    pub-sub-domain: false # false = Queue	true = Topic	default is false
    

